### ISSUE TITLE
Issue with docking

### ISSUE THREAD

**Issue by perryhuynh** [tantinevincent/Onegai-ooyodosan#33]
Everytime it comes to repair, I'm getting these errors:

Traceback (most recent call last):
  File "/home/user/Onegai-ooyodosan/main.sikuli/main.py", line 148, in <module> mainloopWithException()
  File "/home/user/Onegai-ooyodosan/main.sikuli/main.py", line 30, in wrapped return f(*args, **kwargs)
  File "/home/user/Onegai-ooyodosan/main.sikuli/main.py", line 66, in mainloopWithException doAllJob(count)
  File "/home/user/Onegai-ooyodosan/main.sikuli/main.py", line 66, in mainloopWithException doAllJob(count)
  File "/home/user/Onegai-ooyodosan/main.sikuli/main.py", line 30, in wrapped return f(*args, **kwargs)
  File "/home/user/Onegai-ooyodosan/main.sikuli/main.py", line 50, in doAllJob docking_runner.run()
  File "./common.sikuli/common.py", line 7, in wrapped return f(*args, **kwargs)
  File "./composite_runner.sikuli/composite_runner.py", line 15, in run still_running = runner.run()
  File "./common.sikuli/common.py", line 7, in wrapped return f(*args, **kwargs)
  File "./docking_runner.sikuli/docking_runner.py", line 26, in run ships = self.__list_repairing_candidate(self.is_fight, chonse_no_fight_ships_flag)
  File "./common.sikuli/common.py", line 7, in wrapped return f(*args, **kwargs)
  File "./docking_runner.sikuli/docking_runner.py", line 55, in _DockingRunner__list_repairing_candidate ships += self._get_not_in_fleets_ships()
  File "./common.sikuli/common.py", line 7, in wrapped return f(*args, **kwargs)
  File "./docking_runner.sikuli/docking_runner.py", line 75, in _get_not_in_fleets_ships region = Region(location.getX()-200, location.getY()-20, 500, 40)
  File "/usr/share/sikuli/Lib/sikuli/Region.py", line 20, in __init__ JRegion.__init__(self, args[0], args[1], args[2], args[3])
TypeError: org.python.proxies.sikuli.Region$Region$0(): 1st arg can't be coerced to int

**Comment by tantinevincent** [comment]
what browser?

**Comment by perryhuynh** [comment]
Was using chromium, it wasn't working with sikuli-ide but it works fine now with the sikuli-script.jar
